//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class annualtbl
    {
        public int Id { get; set; }
        public Nullable<int> Rollno { get; set; }
        public string Feetype { get; set; }
        public Nullable<int> Fees { get; set; }
        public Nullable<int> Latefee { get; set; }
        public Nullable<int> Feerec { get; set; }
        public Nullable<System.DateTime> Dor { get; set; }
    
        public virtual admissiontbl admissiontbl { get; set; }
    }
}
