//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class studdbEntities : DbContext
    {
        public studdbEntities()
            : base("name=studdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<admissiontbl> admissiontbls { get; set; }
        public DbSet<annualtbl> annualtbls { get; set; }
        public DbSet<coursetbl> coursetbls { get; set; }
        public DbSet<finetbl> finetbls { get; set; }
    }
}
